const DEFAULT={
  site:{bioText:'Nội dung giới thiệu BS Lê Nam Hùng sẽ được cập nhật.',careerText:'Thông tin quá trình công tác sẽ được cập nhật.',expertiseText:'Sản khoa, Phụ khoa, Vô sinh – Hiếm muộn, Siêu âm, Hậu sản.',researchText:'Thông tin nghiên cứu khoa học sẽ được cập nhật.'},
  specialties:[{name:'Sản khoa',icon:'🤰',desc:'Thai kỳ, theo dõi thai và chăm sóc mẹ.'},{name:'Phụ khoa',icon:'🩺',desc:'Khám, tư vấn và các bệnh lý phụ khoa.'},{name:'Vô sinh – Hiếm muộn',icon:'🌱',desc:'Tư vấn sức khỏe sinh sản và hiếm muộn.'},{name:'Siêu âm',icon:'🖥️',desc:'Siêu âm và giải thích các thông tin cần lưu ý.'},{name:'Hậu sản',icon:'🌿',desc:'Chăm sóc mẹ sau sinh và các vấn đề hậu sản.'}],
  services:['Khám Sản khoa','Khám Phụ khoa','Vô sinh – Hiếm muộn','Siêu âm','Hậu sản'],
  clinic:{info:'',booking:'',phone:'',zalo:'http://zaloapp.com/qr/p/quocjkn8vcrk',zaloQr:'zalo-qr.jpg',address:'',hours:'',mapUrl:''},
  articles:[]
};
let client=null,D=structuredClone(DEFAULT);
const $=id=>document.getElementById(id);
function cloneDefault(){return JSON.parse(JSON.stringify(DEFAULT))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function ensureData(){D={...cloneDefault(),...D,site:{...cloneDefault().site,...(D.site||{})},clinic:{...cloneDefault().clinic,...(D.clinic||{})},specialties:Array.isArray(D.specialties)?D.specialties:[],services:Array.isArray(D.services)?D.services:[],articles:Array.isArray(D.articles)?D.articles:[]}}
function setStatus(text,ok=true){const e=$('status');e.textContent=text;e.hidden=false;e.className='status '+(ok?'ok':'err');clearTimeout(setStatus.t);setStatus.t=setTimeout(()=>e.hidden=true,4200)}
function gotoSection(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===name));document.querySelectorAll('.admin-section').forEach(s=>s.classList.toggle('active',s.dataset.section===name));window.scrollTo({top:0,behavior:'smooth'})}
async function isAdmin(){const {data,error}=await client.rpc('is_admin');if(error)return {ok:false,error:error.message};return {ok:data===true,error:null}}
async function boot(){
  if(!window.supabase||!window.SUPABASE_URL?.startsWith('http')){location.href='admin-login.html';return}
  client=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
  const {data:{session}}=await client.auth.getSession();if(!session){location.href='admin-login.html';return}
  const guard=await isAdmin();if(!guard.ok){setStatus('Tài khoản này không có quyền quản trị.',false);await client.auth.signOut();setTimeout(()=>location.href='admin-login.html',1000);return}
  const {data,error}=await client.from('site_content').select('content').eq('id',1).maybeSingle();if(error){setStatus('Không đọc được dữ liệu: '+error.message,false);return}
  if(data?.content)D=data.content;ensureData();renderAll();
}
function renderAll(){renderAbout();renderSpecs();renderServices();renderArticles();renderClinic();renderStats()}
function renderAbout(){$('bioText').value=D.site.bioText||'';$('careerText').value=D.site.careerText||'';$('expertiseText').value=D.site.expertiseText||'';$('researchText').value=D.site.researchText||''}
function renderSpecs(){const root=$('specList');if(!D.specialties.length){root.innerHTML='<div class="empty">Chưa có chuyên môn nào.</div>';return}root.innerHTML=D.specialties.map((x,i)=>`<div class="item"><input class="inline-input" data-spec="icon" data-i="${i}" value="${esc(x.icon||'')}" aria-label="Biểu tượng"><div><input class="inline-input" data-spec="name" data-i="${i}" value="${esc(x.name||'')}" placeholder="Tên chuyên môn"></div><div><textarea class="inline-input" data-spec="desc" data-i="${i}" rows="3" placeholder="Mô tả ngắn">${esc(x.desc||'')}</textarea></div><div class="item-actions"><button class="danger-btn" onclick="delSpec(${i})">Xóa</button></div></div>`).join('')}
function renderServices(){const root=$('serviceList');root.innerHTML=D.services.map((x,i)=>`<div class="service-row"><input class="inline-input service-input" data-i="${i}" value="${esc(x)}" placeholder="Tên dịch vụ"><button class="danger-btn" onclick="delService(${i})">Xóa</button></div>`).join('')||'<div class="empty">Chưa có dịch vụ.</div>'}
function renderArticles(){const root=$('articleList');if(!D.articles.length){root.innerHTML='<div class="empty">Chưa có bài viết. Bấm “＋ Thêm bài viết” để bắt đầu.</div>';return}root.innerHTML=D.articles.map((a,i)=>{const opts=D.specialties.map(s=>`<option ${a.specialty===s.name?'selected':''}>${esc(s.name)}</option>`).join('');const published=a.published!==false;return `<div class="article-editor"><div class="article-top"><input class="inline-input" data-a="title" data-i="${i}" value="${esc(a.title||'')}" placeholder="Tiêu đề bài viết"><select class="inline-input" data-a="specialty" data-i="${i}">${opts||'<option>Sản khoa</option>'}</select><button class="danger-btn" onclick="delArticle(${i})">Xóa</button></div><div class="article-body"><div class="article-meta"><input class="inline-input" data-a="image" data-i="${i}" value="${esc(a.image||'')}" placeholder="URL ảnh đại diện (không bắt buộc)"><label class="toggle"><input type="checkbox" data-a-pub="${i}" ${published?'checked':''}> Xuất bản bài viết</label></div><input class="inline-input" data-a="desc" data-i="${i}" value="${esc(a.desc||'')}" placeholder="Mô tả ngắn"><textarea class="inline-input" data-a="content" data-i="${i}" rows="7" placeholder="Nội dung bài viết...">${esc(a.content||'')}</textarea></div></div>`}).join('')}
function renderClinic(){D.clinic.zalo=D.clinic.zalo||'http://zaloapp.com/qr/p/quocjkn8vcrk';D.clinic.zaloQr=D.clinic.zaloQr||'zalo-qr.jpg';$('clinicInfo').value=D.clinic.info||'';$('bookingText').value=D.clinic.booking||'';$('address').value=D.clinic.address||'';$('hours').value=D.clinic.hours||'';$('phone').value=D.clinic.phone||'';$('zalo').value=D.clinic.zalo;$('zaloQr').value=D.clinic.zaloQr;$('mapUrl').value=D.clinic.mapUrl||''}
function renderStats(){$('statSpecialties').textContent=D.specialties.length;$('statServices').textContent=D.services.length;$('statArticles').textContent=D.articles.length;$('statPublished').textContent=D.articles.filter(x=>x.published!==false).length}
function collect(){ensureData();D.site.bioText=$('bioText').value;D.site.careerText=$('careerText').value;D.site.expertiseText=$('expertiseText').value;D.site.researchText=$('researchText').value;D.clinic.info=$('clinicInfo').value;D.clinic.booking=$('bookingText').value;D.clinic.address=$('address').value;D.clinic.hours=$('hours').value;D.clinic.phone=$('phone').value;D.clinic.zalo=$('zalo').value||'http://zaloapp.com/qr/p/quocjkn8vcrk';D.clinic.zaloQr=$('zaloQr').value||'zalo-qr.jpg';D.clinic.mapUrl=$('mapUrl').value;document.querySelectorAll('[data-spec]').forEach(el=>{D.specialties[+el.dataset.i][el.dataset.spec]=el.value});document.querySelectorAll('.service-input').forEach(el=>D.services[+el.dataset.i]=el.value);document.querySelectorAll('[data-a]').forEach(el=>{D.articles[+el.dataset.i][el.dataset.a]=el.value});document.querySelectorAll('[data-a-pub]').forEach(el=>D.articles[+el.dataset.aPub].published=el.checked)}
window.delSpec=i=>{collect();D.specialties.splice(i,1);renderAll()};window.delService=i=>{collect();D.services.splice(i,1);renderAll()};window.delArticle=i=>{collect();D.articles.splice(i,1);renderAll()};
$('addSpec').onclick=()=>{collect();D.specialties.push({name:'Chuyên môn mới',icon:'＋',desc:'Mô tả chuyên môn mới'});renderAll();gotoSection('specialties')};
$('addService').onclick=()=>{collect();D.services.push('Dịch vụ mới');renderAll();gotoSection('services')};
$('addArticle').onclick=()=>{collect();D.articles.unshift({title:'Bài viết mới',specialty:D.specialties[0]?.name||'Sản khoa',desc:'',content:'',image:'',published:false});renderAll();gotoSection('articles')};
async function save(){collect();const {data:{session}}=await client.auth.getSession();if(!session){location.href='admin-login.html';return}const guard=await isAdmin();if(!guard.ok){setStatus('Phiên quản trị không hợp lệ.',false);return}setStatus('Đang lưu...');const {error}=await client.from('site_content').upsert({id:1,content:D,updated_at:new Date().toISOString(),updated_by:session.user.id});if(error)setStatus('Lưu thất bại: '+error.message,false);else{setStatus('Đã lưu thành công lên hệ thống.');renderStats()}}
$('saveBtn').onclick=save;$('saveBtnBottom').onclick=save;$('logoutBtn').onclick=async()=>{await client.auth.signOut();location.href='admin-login.html'};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>gotoSection(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>gotoSection(b.dataset.go));
boot();
