const DEFAULT={site:{bioText:'Nội dung giới thiệu BS Lê Nam Hùng sẽ được cập nhật.',careerText:'Thông tin quá trình công tác sẽ được cập nhật.',expertiseText:'Sản khoa, Phụ khoa, Vô sinh – Hiếm muộn, Siêu âm, Hậu sản.',researchText:'Thông tin nghiên cứu khoa học sẽ được cập nhật.'},specialties:[{name:'Sản khoa',icon:'🤰',desc:'Thai kỳ, theo dõi thai và chăm sóc mẹ.'},{name:'Phụ khoa',icon:'🩺',desc:'Khám, tư vấn và các bệnh lý phụ khoa.'},{name:'Vô sinh – Hiếm muộn',icon:'🌱',desc:'Tư vấn sức khỏe sinh sản và hiếm muộn.'},{name:'Siêu âm',icon:'🖥️',desc:'Siêu âm và giải thích các thông tin cần lưu ý.'},{name:'Hậu sản',icon:'🌿',desc:'Chăm sóc mẹ sau sinh và các vấn đề hậu sản.'}],services:['Khám Sản khoa','Khám Phụ khoa','Vô sinh – Hiếm muộn','Siêu âm','Hậu sản'],clinic:{info:'',booking:'',phone:'',zalo:'http://zaloapp.com/qr/p/quocjkn8vcrk',zaloQr:'zalo-qr.jpg',address:'',hours:'',mapUrl:''},articles:[]};
let client=null,D=structuredClone(DEFAULT),editingArticleIndex=-1;
const $=id=>document.getElementById(id);
const cloneDefault=()=>JSON.parse(JSON.stringify(DEFAULT));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function ensureData(){const base=cloneDefault();D={...base,...D,site:{...base.site,...(D.site||{})},clinic:{...base.clinic,...(D.clinic||{})},specialties:Array.isArray(D.specialties)?D.specialties:[],services:Array.isArray(D.services)?D.services:[],articles:Array.isArray(D.articles)?D.articles:[]};D.services=D.services.map(x=>typeof x==='string'?{name:x,desc:'',published:true}:({...x,name:x.name||'Dịch vụ mới',desc:x.desc||'',published:x.published!==false}));}
function setStatus(text,ok=true){const e=$('status');e.textContent=text;e.hidden=false;e.className='status '+(ok?'ok':'err');clearTimeout(setStatus.t);setStatus.t=setTimeout(()=>e.hidden=true,4200)}
function gotoSection(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===name));document.querySelectorAll('.admin-section').forEach(s=>s.classList.toggle('active',s.dataset.section===name));window.scrollTo({top:0,behavior:'smooth'})}
async function isAdmin(){const {data,error}=await client.rpc('is_admin');return {ok:!error&&data===true,error:error?.message||null}}
async function boot(){if(!window.supabase||!window.SUPABASE_URL?.startsWith('http')){location.href='admin-login.html';return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const {data:{session}}=await client.auth.getSession();if(!session){location.href='admin-login.html';return}const guard=await isAdmin();if(!guard.ok){setStatus('Tài khoản này không có quyền quản trị.',false);await client.auth.signOut();setTimeout(()=>location.href='admin-login.html',1000);return}const {data,error}=await client.from('site_content').select('content').eq('id',1).maybeSingle();if(error){setStatus('Không đọc được dữ liệu: '+error.message,false);return}if(data?.content)D=data.content;ensureData();renderAll()}
function renderAll(){renderAbout();renderSpecs();renderServices();renderArticlesList();renderClinic();renderStats()}
function renderAbout(){$('bioText').value=D.site.bioText||'';$('careerText').value=D.site.careerText||'';$('expertiseText').value=D.site.expertiseText||'';$('researchText').value=D.site.researchText||''}
function renderSpecs(){const root=$('specList');if(!D.specialties.length){root.innerHTML='<div class="empty">Chưa có chuyên môn nào.</div>';return}root.innerHTML=D.specialties.map((x,i)=>`<div class="item"><input class="inline-input small" data-spec="icon" data-i="${i}" value="${esc(x.icon||'')}" aria-label="Biểu tượng"><div><input class="inline-input" data-spec="name" data-i="${i}" value="${esc(x.name||'')}" placeholder="Tên chuyên môn"><textarea class="inline-input" data-spec="desc" data-i="${i}" rows="2" placeholder="Mô tả ngắn">${esc(x.desc||'')}</textarea></div><div class="item-actions"><button class="danger-btn" data-del-spec="${i}">Xóa</button></div></div>`).join('');root.querySelectorAll('[data-del-spec]').forEach(b=>b.onclick=()=>{collect();const i=+b.dataset.delSpec;if(confirm('Xóa chuyên môn này? Các bài viết vẫn được giữ lại.')){D.specialties.splice(i,1);renderAll()}})}
function renderServices(){const root=$('serviceList');if(!D.services.length){root.innerHTML='<div class="empty">Chưa có dịch vụ.</div>';return}root.innerHTML=D.services.map((x,i)=>`<div class="service-admin-card"><div class="service-admin-main"><input class="inline-input" data-svc="name" data-i="${i}" value="${esc(x.name)}" placeholder="Tên dịch vụ"><textarea class="inline-input" data-svc="desc" data-i="${i}" rows="2" placeholder="Mô tả ngắn (không bắt buộc)">${esc(x.desc||'')}</textarea></div><label class="switch-row"><input type="checkbox" data-svc-pub="${i}" ${x.published!==false?'checked':''}><span>Hiển thị</span></label><button class="danger-btn" data-del-service="${i}">Xóa</button></div>`).join('');root.querySelectorAll('[data-del-service]').forEach(b=>b.onclick=()=>{collect();const i=+b.dataset.delService;if(confirm('Xóa dịch vụ này?')){D.services.splice(i,1);renderAll()}})}
function renderArticlesList(){const root=$('articleList');if(!D.articles.length){root.innerHTML='<div class="empty">Chưa có bài viết. Bấm “＋ Thêm bài viết” để bắt đầu.</div>';return}const list=[...D.articles].map((a,i)=>({a,i}));root.innerHTML=list.map(({a,i})=>`<div class="article-row"><div class="article-row-copy"><div class="article-row-top"><span class="tag">${esc(a.specialty||'Chưa phân loại')}</span><span class="status-pill ${a.published!==false?'on':'off'}">${a.published!==false?'Đã xuất bản':'Bản nháp'}</span></div><h3>${esc(a.title||'Bài viết chưa có tiêu đề')}</h3><p>${esc(a.desc||'Chưa có mô tả ngắn.')}</p></div><div class="article-row-actions"><button class="secondary-btn" data-edit-article="${i}">Sửa</button><button class="danger-btn" data-del-article="${i}">Xóa</button></div></div>`).join('');root.querySelectorAll('[data-edit-article]').forEach(b=>b.onclick=()=>openArticleEditor(+b.dataset.editArticle));root.querySelectorAll('[data-del-article]').forEach(b=>b.onclick=()=>{collect();const i=+b.dataset.delArticle;if(confirm('Xóa bài viết này?')){D.articles.splice(i,1);renderAll()}})}
function renderClinic(){const c=D.clinic||{};$('clinicInfo').value=c.info||'';$('bookingText').value=c.booking||'';$('address').value=c.address||'';$('hours').value=c.hours||'';$('phone').value=c.phone||'';$('zalo').value=c.zalo||'';$('zaloQr').value=c.zaloQr||'zalo-qr.jpg';$('mapUrl').value=c.mapUrl||''}
function renderStats(){$('statSpecialties').textContent=D.specialties.length;$('statServices').textContent=D.services.length;$('statArticles').textContent=D.articles.length;$('statPublished').textContent=D.articles.filter(x=>x.published!==false).length}
function collect(){ensureData();D.site.bioText=$('bioText').value;D.site.careerText=$('careerText').value;D.site.expertiseText=$('expertiseText').value;D.site.researchText=$('researchText').value;Object.assign(D.clinic,{info:$('clinicInfo').value,booking:$('bookingText').value,address:$('address').value,hours:$('hours').value,phone:$('phone').value,zalo:$('zalo').value,zaloQr:$('zaloQr').value||'zalo-qr.jpg',mapUrl:$('mapUrl').value});document.querySelectorAll('[data-spec]').forEach(el=>{D.specialties[+el.dataset.i][el.dataset.spec]=el.value});document.querySelectorAll('[data-svc]').forEach(el=>{D.services[+el.dataset.i][el.dataset.svc]=el.value});document.querySelectorAll('[data-svc-pub]').forEach(el=>{D.services[+el.dataset.svcPub].published=el.checked})}
function openArticleEditor(index=-1){collect();editingArticleIndex=index;const a=index>=0?D.articles[index]:{title:'',specialty:D.specialties[0]?.name||'Sản khoa',desc:'',image:'',content:'',published:false};$('modalTitle').textContent=index>=0?'Sửa bài viết':'Thêm bài viết';$('editTitle').value=a.title||'';$('editDesc').value=a.desc||'';$('editImage').value=a.image||'';$('editPublished').checked=a.published!==false;$('editSpecialty').innerHTML=D.specialties.map(s=>`<option value="${esc(s.name)}">${esc(s.name)}</option>`).join('')||'<option>Sản khoa</option>';$('editSpecialty').value=a.specialty||D.specialties[0]?.name||'Sản khoa';$('editContent').innerHTML=a.content||'';$('editorModal').hidden=false;setTimeout(()=>$('editTitle').focus(),50)}
function closeArticleEditor(){$('editorModal').hidden=true;editingArticleIndex=-1}
function saveArticleFromModal(){collect();const obj={title:$('editTitle').value.trim()||'Bài viết mới',specialty:$('editSpecialty').value||D.specialties[0]?.name||'Sản khoa',desc:$('editDesc').value.trim(),image:$('editImage').value.trim(),content:$('editContent').innerHTML.trim(),published:$('editPublished').checked};if(editingArticleIndex<0)D.articles.unshift(obj);else D.articles[editingArticleIndex]=obj;closeArticleEditor();renderAll();gotoSection('articles');setStatus('Đã cập nhật bài viết trong bộ nhớ. Hãy bấm “Lưu thay đổi” để ghi lên hệ thống.')}
$('addSpec').onclick=()=>{collect();D.specialties.push({name:'Chuyên môn mới',icon:'＋',desc:'Mô tả chuyên môn mới'});renderAll();gotoSection('specialties')};
$('addService').onclick=()=>{collect();D.services.push({name:'Dịch vụ mới',desc:'',published:true});renderAll();gotoSection('services')};
$('addArticle').onclick=()=>openArticleEditor(-1);
async function save(){collect();const {data:{session}}=await client.auth.getSession();if(!session){location.href='admin-login.html';return}const guard=await isAdmin();if(!guard.ok){setStatus('Phiên quản trị không hợp lệ.',false);return}setStatus('Đang lưu...');const {error}=await client.from('site_content').upsert({id:1,content:D,updated_at:new Date().toISOString(),updated_by:session.user.id});if(error)setStatus('Lưu thất bại: '+error.message,false);else{setStatus('Đã lưu thành công lên hệ thống.');renderStats()}}
$('saveBtn').onclick=save;$('saveBtnBottom').onclick=save;$('logoutBtn').onclick=async()=>{await client.auth.signOut();location.href='admin-login.html'};document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>gotoSection(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>gotoSection(b.dataset.go));
$('closeModal').onclick=closeArticleEditor;$('cancelModal').onclick=closeArticleEditor;$('editorModal').querySelector('.modal-backdrop').onclick=closeArticleEditor;$('saveArticle').onclick=saveArticleFromModal;document.querySelectorAll('.editor-toolbar button').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,null);$('editContent').focus()});
boot();
