const DEFAULT_DATA={site:{aboutIntro:'Bác sĩ chuyên ngành Sản Phụ khoa với định hướng chia sẻ kiến thức y khoa dễ hiểu và đồng hành cùng người bệnh.',bioText:'Nội dung giới thiệu BS Lê Nam Hùng sẽ được cập nhật.',careerText:'Thông tin quá trình công tác sẽ được cập nhật.',expertiseText:'Sản khoa, Phụ khoa, Vô sinh – Hiếm muộn, Siêu âm, Hậu sản.',researchText:'Thông tin nghiên cứu khoa học sẽ được cập nhật.'},specialties:[{name:'Sản khoa',icon:'🤰',desc:'Thai kỳ, theo dõi thai và chăm sóc mẹ.'},{name:'Phụ khoa',icon:'🩺',desc:'Khám, tư vấn và các bệnh lý phụ khoa.'},{name:'Vô sinh – Hiếm muộn',icon:'🌱',desc:'Tư vấn sức khỏe sinh sản và hiếm muộn.'},{name:'Siêu âm',icon:'🖥️',desc:'Siêu âm và giải thích các thông tin cần lưu ý.'},{name:'Hậu sản',icon:'🌿',desc:'Chăm sóc mẹ sau sinh và các vấn đề hậu sản.'}],services:['Khám Sản khoa','Khám Phụ khoa','Vô sinh – Hiếm muộn','Siêu âm','Hậu sản'],clinic:{info:'Địa chỉ, thời gian làm việc và thông tin liên hệ sẽ được cập nhật.',booking:'Liên hệ trực tiếp để được hướng dẫn lịch khám.',phone:'',zalo:'http://zaloapp.com/qr/p/quocjkn8vcrk',zaloQr:'zalo-qr.jpg'},articles:[{title:'Những điều cần lưu ý khi theo dõi thai kỳ',specialty:'Sản khoa',desc:'Nội dung mẫu để anh thay thế bằng bài viết thực tế của mình.'},{title:'Khi nào nên đi khám phụ khoa?',specialty:'Phụ khoa',desc:'Nội dung mẫu để anh thay thế bằng bài viết thực tế của mình.'},{title:'Một số thông tin cơ bản về siêu âm thai',specialty:'Siêu âm',desc:'Nội dung mẫu để anh thay thế bằng bài viết thực tế của mình.'}]};
let DATA=structuredClone(DEFAULT_DATA);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function loadData(){
 try{if(window.supabase&&SUPABASE_URL.startsWith('http')){const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const {data,error}=await client.from('site_content').select('content').eq('id',1).maybeSingle();if(!error&&data?.content)return data.content}}catch(e){}
 return DATA;
}
async function render(){
 DATA=await loadData();DATA.clinic=DATA.clinic||{};DATA.clinic.zalo=DATA.clinic.zalo||'http://zaloapp.com/qr/p/quocjkn8vcrk';DATA.clinic.zaloQr=DATA.clinic.zaloQr||'zalo-qr.jpg';
 document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('bioText').textContent=DATA.site.bioText;document.getElementById('careerText').textContent=DATA.site.careerText;document.getElementById('expertiseText').textContent=DATA.site.expertiseText;document.getElementById('researchText').textContent=DATA.site.researchText;document.getElementById('clinicInfo').textContent=DATA.clinic.info;document.getElementById('bookingText').textContent=DATA.clinic.booking;
 const sg=document.getElementById('specialtyGrid');sg.innerHTML=DATA.specialties.map(x=>`<a class="specialty-card" href="#articles" data-specialty="${esc(x.name)}"><div class="specialty-icon">${esc(x.icon)}</div><h3>${esc(x.name)}</h3><p>${esc(x.desc)}</p></a>`).join('');
 const svc=document.getElementById('serviceGrid');svc.innerHTML=DATA.services.map(x=>`<div class="service-item"><i>✓</i><span>${esc(x)}</span></div>`).join('')+`<div class="service-item"><i>＋</i><span>Dịch vụ khác (có thể mở rộng)</span></div>`;
 const phone=document.getElementById('phoneBtn'),z=document.getElementById('zaloBtn');if(DATA.clinic.phone){phone.href='tel:'+DATA.clinic.phone;phone.textContent='Gọi '+DATA.clinic.phone}else{phone.href='#contact'}if(DATA.clinic.zalo){z.href=DATA.clinic.zalo;z.target='_blank'}else{z.href='#contact'}const qr=document.getElementById('zaloQr'),qrLink=document.getElementById('zaloQrLink');if(DATA.clinic.zaloQr)qr.src=DATA.clinic.zaloQr;if(DATA.clinic.zalo){qrLink.href=DATA.clinic.zalo;qrLink.target='_blank'}if(qr){qr.style.cursor='pointer';qr.onclick=()=>{if(DATA.clinic.zalo)window.open(DATA.clinic.zalo,'_blank')}}
 const acts=document.getElementById('contactActions');acts.innerHTML='';if(DATA.clinic.phone)acts.innerHTML+=`<a class="btn primary" href="tel:${esc(DATA.clinic.phone)}">Gọi điện</a>`;if(DATA.clinic.zalo)acts.innerHTML+=`<a class="btn secondary" href="${esc(DATA.clinic.zalo)}" target="_blank">Zalo</a>`;
 renderArticles();bindSpecialties();
}
function renderArticles(filter=''){const q=document.getElementById('searchInput')?.value.trim().toLowerCase()||'';const rows=(DATA.articles||[]).filter(a=>a.published!==false&&(!filter||a.specialty===filter)&&(!q||(a.title+a.desc+a.specialty+a.content).toLowerCase().includes(q)));document.getElementById('articleGrid').innerHTML=rows.map((a,i)=>`<article class="article-card"><div class="body">${a.image?`<img src="${esc(a.image)}" alt="${esc(a.title)}" loading="lazy">`:''}<div class="article-tag">${esc(a.specialty)}</div><h3>${esc(a.title)}</h3><p>${esc(a.desc)}</p><a href="#articles" data-article-index="${i}">Đọc bài viết →</a></div></article>`).join('');document.getElementById('emptyState').hidden=rows.length>0;document.querySelectorAll('[data-article-index]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openArticle(rows[+el.dataset.articleIndex])}));}
function openArticle(a){let m=document.getElementById('articleModal');if(!m){m=document.createElement('div');m.id='articleModal';m.className='article-modal';m.innerHTML='<div class="article-modal-backdrop"></div><div class="article-modal-card"><button class="article-modal-close" aria-label="Đóng">×</button><div class="article-modal-content"></div></div>';document.body.appendChild(m);m.querySelector('.article-modal-close').onclick=()=>m.classList.remove('show');m.querySelector('.article-modal-backdrop').onclick=()=>m.classList.remove('show');}m.querySelector('.article-modal-content').innerHTML=`<div class="article-tag">${esc(a.specialty||'')}</div><h2>${esc(a.title||'')}</h2>${a.image?`<img src="${esc(a.image)}" alt="${esc(a.title||'')}">`:''}<p>${esc(a.desc||'')}</p><div class="article-full">${esc(a.content||'').replace(/\n/g,'<br>')}</div>`;m.classList.add('show')}
function bindSpecialties(){document.querySelectorAll('.specialty-card').forEach(el=>el.addEventListener('click',()=>{const f=el.dataset.specialty;setTimeout(()=>renderArticles(f),50)}));}
document.getElementById('searchInput')?.addEventListener('input',()=>renderArticles());document.getElementById('navToggle')?.addEventListener('click',()=>document.getElementById('mainNav').classList.toggle('open'));render();
